function API:CreateCmd(Header, Description, Callback,IsHide,Extra,IsPre,plsdonotlower)
		API:CreateCmd("removecars", "deletes all cars that are not seated", function(args)
		API:CreateCmd("lag", "lags the server", function(args)
		API:CreateCmd("kick", "!KICKS TIGER ADMIN USERS ONLY! SAY IN CHAT", function(args)
		API:CreateCmd("prefix", "Sets a different prefix", function(args)
		API:CreateCmd("unadmin", "Unadmins a player", function(args)
		API:CreateCmd("pp", "sus", function(args)
		API:CreateCmd("jeff", "Jeff the killer npc (rejoin to disable)", function(args)
		API:CreateCmd("opendoors", "Opens every single door", function(args)
		API:CreateCmd("loopopendoors", "Opens every single door on loop", function(args)
		API:CreateCmd("grabknife", "Cool script [REJOIN TO STOP]", function(args)
		API:CreateCmd("admin", "The selected player can use certain commands", function(args)
		API:CreateCmd("admins", "Tells you all admins", function(args)
		API:CreateCmd("crashserver", "Crashes the server", function(args)
		API:CreateCmd("oneshot", "Makes a gun oneshot", function(args)
		API:CreateCmd("anticrash", "Tries to stop simple crashes (DOESNT WORK WITH TIGER ADMIN CRASH)", function(args)
		API:CreateCmd("virus", "Anyone who touches the player dies", function(args)
		API:CreateCmd("unvirus", "Removes virus from player", function(args)
		API:CreateCmd("lagspike", "Freezes everyones screen for some seconds", function(args)
		API:CreateCmd("ff", "Forcefield", function(args)
		API:CreateCmd("minigun", "makes a minigun", function(args)
		API:CreateCmd("music", "plays sound id in your game", function(args)
		API:CreateCmd("spam", "spams a message in game", function(args)
		API:CreateCmd("roast", "spams a message in game", function(args)
		API:CreateCmd("joinlogs", "tells you who is leaving and joining", function(args)
		API:CreateCmd("antifling", "prevents players from flinging you", function(args)
		API:CreateCmd("mkill", "kills player by teleport", function(args)
		API:CreateCmd("loopmkill", "kills player by teleport loopkill", function(args)
		API:CreateCmd("unloopmkill", "kills player by teleport loopkill", function(args)
		API:CreateCmd("godmode", "Turns on all settings that prevent you from harm", function(args)
		API:CreateCmd("superknife", "One shot knife", function(args)
		API:CreateCmd("autoadmin", "Admins someone even if you leave and rejoin", function(args)
		API:CreateCmd("unautoadmin", "unauto admins a player", function(args)
		API:CreateCmd("earrape", "spams sounds", function(args)
	API:CreateCmd("drag", "Enables draggable mode for all tiger guis", function(args)
	API:CreateCmd("js", "owner", function(args)
	API:CreateCmd("doors", "prevents players from flinging you", function(args)
	API:CreateCmd("copyteam", "copies a player team looped", function(args)
	API:CreateCmd("speed", "sets your players speed", function(args)
	API:CreateCmd("jump", "sets your players jumppower", function(args)
	API:CreateCmd("uncopyteam", "stops copying a players team", function(args)
	API:CreateCmd("kill", "Kills a player", function(args)
	API:CreateCmd("arrest", "Arrests the targeted player", function(args)
	API:CreateCmd("loopkill", "Kills a player over and over until stopped", function(args)
	API:CreateCmd("lk", "Kills a player over and over until stopped", function(args)
	API:CreateCmd("unloopkill", "Stops loopkilling a player", function(args)
	API:CreateCmd("unlk", "Stops loopkilling a player", function(args)
	API:CreateCmd("tase", "Tases the target", function(args)
	API:CreateCmd("heaven", "Teleports a player to the void", function(args)
	API:CreateCmd("void", "Teleports a player to the void", function(args)
	API:CreateCmd("whitelist", "Prevents commands from harming the target", function(args)
	API:CreateCmd("unwhitelist", "unwhitelists a target", function(args)
	API:CreateCmd("view", "Watches the selected target", function(args)
	API:CreateCmd("bring", "Brings a player to you", function(args)
	API:CreateCmd("addnuke", "Player dies everyone dies", function(args)
	API:CreateCmd("to", "Teleports to a player", function(args)
	API:CreateCmd("cursor ", "Changes mouse icon", function(args)
	API:CreateCmd("goto", "Teleports to a player", function(args)
	API:CreateCmd("clickarrest", "click on someone to arrest them", function(args)
	API:CreateCmd("esp", "shows where all players are", function(args)
	API:CreateCmd("silentaim", "Fire and dont miss", function(args)
	API:CreateCmd("clickkill", "click on someone to kill them", function(args)
	API:CreateCmd("autorespawn", "you die and respawn back", function(args)
	API:CreateCmd("antisit", "Prevents you from sitting", function(args)
	API:CreateCmd("antitouch", "Kills anyone who touches you", function(args)
	API:CreateCmd("arrestaura", "Kills anyone close to you", function(args)
	API:CreateCmd("killaura", "Kills anyone close to you", function(args)
	API:CreateCmd("autoitems", "Gets guns after you die", function(args)
	API:CreateCmd("antiarrest", "!!TRYS!! to Prevents you from getting arrested", function(args)
	API:CreateCmd("noinvite", "disables discord invite", function(args)
	API:CreateCmd("antipunch", "prevents anyone from punching you", function(args)
	API:CreateCmd("antishield", "Deletes other peoples shields", function(args)
	API:CreateCmd("spawnguns", "Loop kills you to spawn guns", function(args)
	API:CreateCmd("shootback", "Kills anyone who shoots you ", function(args)
	API:CreateCmd("onepunch", "Insta-kills anyone you punch", function(args)
	API:CreateCmd("antitase", "Prevents you from getting tased", function(args)
	API:CreateCmd("neutral", "Changes your team to Neutral", function(args)
	API:CreateCmd("inmate", "Changes your team to inmate", function(args)
	API:CreateCmd("guard", "Changes your team to guard", function(args)
	API:CreateCmd("criminal", "Changes your team to criminal or a person", function(args)
	API:CreateCmd("unview", "Unwatches the selected target", function(args)
	API:CreateCmd("car", "Brings a car to you", function(args)
	API:CreateCmd("opengate", "Opens the main prison gate", function(args)
	API:CreateCmd("fly", "Enter plane mode but dont hit towers", function(args)
	API:CreateCmd("carfly", "Car go flying", function(args)
	API:CreateCmd("uncarfly", "stop the car fly", function(args)
	API:CreateCmd("unfly", "Disables fly", function(args)
	API:CreateCmd("keycard", "Gets a keycard", function(args)
	API:CreateCmd("refresh", "refreshes your character", function(args)
	API:CreateCmd("roof", "", function(args)
	API:CreateCmd("nex", "", function(args)
	API:CreateCmd("prison", "Teleports to location", function(args)
	API:CreateCmd("m4a1", "Gets a M4A1 gun", function(args)
	API:CreateCmd("m9", "Gets a M9 gun", function(args)
	API:CreateCmd("shotgun", "Gets a shotgun", function(args)
	API:CreateCmd("ak", "Gets a ak-47", function(args)
	API:CreateCmd("knife", "Gets a knife", function(args)
	API:CreateCmd("hammer", "Gets a hammer", function(args)
	API:CreateCmd("yard", "Teleports to location", function(args)
	API:CreateCmd("gas", "Teleports to location", function(args)
	API:CreateCmd("cafe", "Teleports to location", function(args)
	API:CreateCmd("bridge", "Teleports to location", function(args)
	API:CreateCmd("lunchroom", "Teleports to location", function(args)
	API:CreateCmd("crimbase", "Teleports to location", function(args)
	API:CreateCmd("cbase", "Teleports to location", function(args)
	API:CreateCmd("armory", "Teleports to location", function(args)
	API:CreateCmd("tower", "Teleports to location", function(args)
	API:CreateCmd("cmds", "Toggles commands gui", function(args)
	API:CreateCmd("rejoin", "rejoins the same server (UNLOADS SCRIPT)", function(args)
	API:CreateCmd("rj", "rejoins the same server (UNLOADS SCRIPT)", function(args)
	API:CreateCmd("re", "refreshes your character", function(args)
	API:CreateCmd("allcmds", "tells you the ammount of commands tiger admin has", function(args)
	API:CreateCmd("serverhop", "Joins a different server", function(args)
	API:CreateCmd("btools", "Destroy walls", function(args)
	API:CreateCmd("guns", "Gets every single gun", function(args)
	API:CreateCmd("items", "Gets every single gun", function(args)
	API:CreateCmd("noclip", "Go through walls", function(args)
	API:CreateCmd("clip", "Disables noclip", function(args)
	API:CreateCmd("autofire", "Mods the gun", function(args)
	API:CreateCmd("fastfire", "hold a tool to mod your gun", function(args)
	API:CreateCmd("infammo", "hold a tool to mod your gun", function(args)
	API:CreateCmd("modgun", "adds superpowers to your gun", function(args)
	API:CreateCmd("autoinfammo", "Always apply inf ammo on all your guns", function(args)
	API:CreateCmd("unload", "Destroys the script unloading it", function(args)
